### ISSUE TITLE
Support for custom scripts

### ISSUE THREAD

**Issue by jceb** [SFTtech/xautocfg#2]
Thank you for this great little tool! I've been searching for a solution for dynamically configuring HIDs upon connect and there seems to be no other good option apart from your project!
I'd love to execute custom scripts depending on whether the device has been enabled / disabled. Would you be open to extending your service? I'm happy to contribute and test.

**Comment by TheJJ** [comment]
sure, it's designed and intended that way :) we could just add paths to scripts that get executed then. can you create a pull request?

what would you like to execute in your script? maybe there's an even better way.

**Comment by jceb** [comment]
Great 👍 I configure a number of things when a new device gets connected:
- limit graphics tablet to one particular screen
- configure natural scrolling
- set the keyboard repeat rate, like xautocfg does
- turn off the notification bell, xset b off
- set track point speed

If we could pass information about the connected device to the script via an environment variable, then the settings could be applied a bit more precisely.
